server:
  port: ${port:8000}
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2zebj150s7a6v277zqo.mysql.rds.aliyuncs.com/1708bfour?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1708bROOT
    #druid的配置
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 打开PSCache，并且指定每个连接上PSCache的大小
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
#redis配置
  redis:
#  数据库索引
    database: 0
#    服务器地址
    host: 127.0.0.1
#    服务器连接端口
    port: 6379
#    链接密码
    password:
#    链接池
    pool:
#    最大连接数（负值表示没有限制）
      max-active: 8
#      最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
#      最大空闲链接
      max-idle: 8
#      最小空闲链接
      min-idle: 0
#    链接超时时间（毫秒）
    timeout: 0
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  jta:
    narayana:
      xa-resource-orphan-filters: stat,wall,log4j
# 别名
mybatis:
  type-aliases-package: com.jk
#日志级别
logging:
  level: info
